apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-slave
  labels:
    name: mysql-slave
spec:
  replicas: 1
  selector:
    name: mysql-slave
  template: 
    metadata: 
      labels: 
        name: mysql-slave
    spec: 
      containers:
      - name: mysql-slave
        image: luoweb/mysql-slave:5.7.21
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "root"
          - name: MYSQL_REPLICATION_USER
            value: "repl"
          - name: MYSQL_REPLICATION_PASSWORD
            value: "repl"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
    name: mysql-slave
spec:
  ports: 
  - port: 3306
    targetPort: 3306
  selector:
    name: mysql-slave
