apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-slave
  labels:
    name: mysql-slave
spec:
  replicas: 1
  selector:
    name: mysql-slave
  template: 
    metadata: 
      labels: 
        name: mysql-slave
    spec: 
      containers:
      - name: slave
        image: luoweb/mysql-slave:latest
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "root"
          - name: MYSQL_REPLICATION_USER
            value: "repl"
          - name: MYSQL_REPLICATION_PASSWORD
            value: "repl"